{% set name = "airflow-code-editor" %}
{% set version = "8.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/airflow_code_editor-{{ version }}.tar.gz
  sha256: 6f82068c45911df977c92f8123fb20ec3738c3a5e98963eb2e9bde39413acfd1

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - apache-airflow
    - fs >=2.4.16
    - pss >=1.44

test:
  imports:
    - airflow_code_editor
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/andreax79/airflow-code-editor
  summary: Apache Airflow code editor and file manager
  license: Apache-2.0
  license_file:
    - LICENSE
    - airflow_code_editor/static/fonts/LICENSE

extra:
  recipe-maintainers:
    - xylar
    - rxm7706
