schema_version: 1

context:
  name: airflow-code-editor
  version: 8.2.0

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/airflow_code_editor-${{ version }}.tar.gz
  sha256: b9bf5b32ba5a59df03b177daca8ec5b87c21a08e8a20afdef765834dde22b118

build:
  number: 1
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - flask
    - fsspec
    - pss >=1.44

tests:
  - python:
      imports:
        - airflow_code_editor
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Apache Airflow code editor and file manager
  license: Apache-2.0
  license_file:
    - LICENSE
    - airflow_code_editor/static/fonts/LICENSE
  homepage: https://github.com/andreax79/airflow-code-editor

extra:
  recipe-maintainers:
    - xylar
    - rxm7706
