schema_version: 1

context:
  name: airflow-code-editor
  version: "8.3.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/airflow_code_editor-${{ version }}.tar.gz
  sha256: f7a44b44e02c62a2b29c83dd21b69462078ae0590135118c998bd09f350a4146

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - setuptools
  run:
    - python >=${{ python_min }}
    - flask
    - fsspec
    - pss >=1.44

tests:
  - python:
      imports:
        - airflow_code_editor
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  summary: Apache Airflow code editor and file manager
  license: Apache-2.0
  license_file:
    - LICENSE
    - airflow_code_editor/static/fonts/LICENSE
  homepage: https://github.com/andreax79/airflow-code-editor

extra:
  recipe-maintainers:
    - xylar
    - rxm7706
